### ISSUE TITLE
Is this meant for public consumption?

### ISSUE THREAD

**Issue by kwerle** [ChemAxon/marvinjs-docker-example#1]
All the dockerfiles I see refer to hub.chemaxon.com - which requires auth.

```
➜  docker run hub.chemaxon.com/cxn-docker-release/chemaxon/mjs-webservice:latest
Unable to find image 'hub.chemaxon.com/cxn-docker-release/chemaxon/mjs-webservice:latest' locally
docker: Error response from daemon: Get https://hub.chemaxon.com/v2/cxn-docker-release/chemaxon/mjs-webservice/manifests/latest: unknown: Authentication is required.
```

**Comment by bzaicsek-cxn** [comment]
Hi!

You are correct!
Yes,  this is meant for "public consumption" as a documentation / example usage.  All of the dockerfiles refer to hub.chemaxon.com which is our public repository (for maven / npm / docker artifacts). This server requires authentication. You can find how to authenticate here: https://chemaxon.com/products/marvin-js/download (on the docker tab). To view the linked page you also have to authenticate, for what you have to register at https://accounts.chemaxon.com/register . But you also must have a license which you can only obtain legally if you have an active user registered to us, so we don't consider this as an issue.

**Comment by bzaicsek-cxn** [comment]
I have forwarded your notice; lets fight together for open repositories! :)

**Comment by kwerle** [comment]
This is frustrating.  We use your product in production, but each of our developers also needs to use it in their development environment.  And, of course, we also need it on our CI machines for integration testing.
Either we need everyone to get their own set of credentials - plus a set for the CI systems - or we need to get one set of credentials and pass them around.  Neither of those is a great solution.  

Do you recommend one of those approaches?  Something else?

**Comment by bzaicsek-cxn** [comment]
After checking all license and compliance information I can tell, that the best option for you would be to have shared cache of those artifacts (like your own docker repo) where you upload all data from us that you want to access. This repository can be updated automatically and that automatism can have a login to our servers.

How ever I must tell the API key we provide is a unique identifier which is independent from your password. If it gets compromised we can revoke and regenerate without the inconvenience of changing your password.

**Comment by kwerle** [comment]
Thank you for doing this investigation and getting me your conclusion - I do appreciate it.
